# ====================================
# PostgreSQL Service for Educational Platform
# ====================================
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: educational-lab
  labels:
    app: postgres
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: postgres
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP
