# ====================================
# Frontend Deployment for Educational Platform
# Angular application served by Nginx
# ====================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: educational-frontend
  namespace: educational-lab
  labels:
    app: educational-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: educational-frontend
  template:
    metadata:
      labels:
        app: educational-frontend
    spec:
      containers:
      - name: frontend
        image: temitayocharles/educational-frontend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: API_URL
          value: "http://educational-backend:8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
