# ====================================
# Redis Service for Educational Platform
# ====================================
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: educational-lab
  labels:
    app: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
