# ====================================
# Backend Deployment for Task Management App
# Go API with PostgreSQL
# ====================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-backend
  namespace: task-management
  labels:
    app: task-management-app
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-management-app
      component: backend
  template:
    metadata:
      labels:
        app: task-management-app
        component: backend
    spec:
      containers:
      - name: backend
        image: temitayocharles/task-backend:latest
        ports:
        - containerPort: 8082
          name: http
        env:
        # Application settings
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: task-config
              key: PORT
        - name: GIN_MODE
          valueFrom:
            configMapKeyRef:
              name: task-config
              key: GIN_MODE
        
        # Database connection string
        - name: DATABASE_URL
          value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=$(DB_SSLMODE)"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: task-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: task-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: task-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: task-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: task-secret
              key: DB_PASSWORD
        - name: DB_SSLMODE
          valueFrom:
            configMapKeyRef:
              name: task-config
              key: DB_SSLMODE
        
        # JWT secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: task-secret
              key: JWT_SECRET
        
        # CORS
        - name: CORS_ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: task-config
              key: CORS_ALLOWED_ORIGINS
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: task-backend
  namespace: task-management
  labels:
    app: task-management-app
    component: backend
spec:
  type: ClusterIP
  selector:
    app: task-management-app
    component: backend
  ports:
  - name: http
    port: 8082
    targetPort: 8082
    protocol: TCP
