# ====================================
# API Deployment for Medical Care System
# .NET Web API with PostgreSQL
# ====================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-api
  namespace: medical-care
  labels:
    app: medical-care-system
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medical-care-system
      component: api
  template:
    metadata:
      labels:
        app: medical-care-system
        component: api
    spec:
      containers:
      - name: api
        image: temitayocharles/medical-api:latest
        ports:
        - containerPort: 5170
          name: http
        env:
        # Application settings
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: medical-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: medical-config
              key: ASPNETCORE_URLS
        
        # Database connection string
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: medical-secret
              key: ConnectionStrings__DefaultConnection
        
        # JWT settings
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: medical-secret
              key: JWT_SECRET
        - name: JWT_ISSUER
          valueFrom:
            secretKeyRef:
              name: medical-secret
              key: JWT_ISSUER
        - name: JWT_AUDIENCE
          valueFrom:
            secretKeyRef:
              name: medical-secret
              key: JWT_AUDIENCE
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 5170
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 5170
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: medical-api
  namespace: medical-care
  labels:
    app: medical-care-system
    component: api
spec:
  type: ClusterIP
  selector:
    app: medical-care-system
    component: api
  ports:
  - name: http
    port: 5170
    targetPort: 5170
    protocol: TCP
