# ====================================
# PostgreSQL Service for Social Media Platform
# ====================================
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: social-lab
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP
