# ====================================
# Frontend Deployment for Social Media Platform
# React Native Web application
# ====================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-frontend
  namespace: social-lab
  labels:
    app: social-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-frontend
  template:
    metadata:
      labels:
        app: social-frontend
    spec:
      containers:
      - name: frontend
        image: temitayocharles/social-frontend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: REACT_APP_API_URL
          value: "http://social-backend:3000"
        - name: REACT_APP_WS_URL
          value: "ws://social-backend:3000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
