# ====================================
# Frontend Service for Weather Application
# ====================================
apiVersion: v1
kind: Service
metadata:
  name: weather-frontend
  namespace: weather-lab
  labels:
    app: weather-frontend
spec:
  type: LoadBalancer
  selector:
    app: weather-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
