# ====================================
# Frontend Deployment for Weather Application
# Vue.js application served by Nginx
# ====================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-frontend
  namespace: weather-lab
  labels:
    app: weather-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-frontend
  template:
    metadata:
      labels:
        app: weather-frontend
    spec:
      containers:
      - name: frontend
        image: temitayocharles/weather-frontend:latest
        imagePullPolicy: Always
        
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        
        env:
        - name: VUE_APP_API_URL
          value: "http://weather-backend:5000"
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      
      restartPolicy: Always
