# ====================================
# Backend Service for Medical Care System
# ====================================
apiVersion: v1
kind: Service
metadata:
  name: medical-backend
  namespace: medical-lab
  labels:
    app: medical-backend
spec:
  type: ClusterIP
  selector:
    app: medical-backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
